#!/bin/bash

dotfile_dir=$(git rev-parse --show-toplevel)

save() {
  cp $HOME/$1 $dotfile_dir/$1
}

restore() {
  cp $dotfile_dir/$1 $HOME/$1 
}

restore .vimrc
restore .gitconfig
restore .bash_aliases
restore .tmux.conf
restore bin/lxc-ssh
restore bin/scan-wifi
restore bin/min_brightness
