#!/bin/bash

save() {
  cp $HOME/$1 $HOME/dotfiles/$1
}

save .vimrc
save .gitconfig
save .bash_aliases
save .tmux.conf
save bin/lxc-ssh
save bin/scan-wifi
save bin/min_brightness
save bin/accept-wifi
